###############################################################################
# Created by write_sdc
###############################################################################
current_design vector_unit
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 14.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[100]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[101]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[102]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[103]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[104]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[105]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[106]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[107]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[108]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[109]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[110]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[111]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[112]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[113]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[114]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[115]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[116]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[117]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[118]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[119]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[120]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[121]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[122]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[123]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[124]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[125]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[126]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[127]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[32]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[33]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[34]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[35]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[36]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[37]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[38]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[39]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[40]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[41]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[42]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[43]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[44]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[45]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[46]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[47]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[48]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[49]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[50]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[51]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[52]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[53]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[54]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[55]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[56]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[57]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[58]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[59]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[60]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[61]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[62]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[63]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[64]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[65]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[66]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[67]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[68]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[69]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[70]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[71]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[72]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[73]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[74]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[75]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[76]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[77]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[78]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[79]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[80]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[81]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[82]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[83]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[84]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[85]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[86]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[87]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[88]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[89]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[90]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[91]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[92]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[93]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[94]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[95]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[96]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[97]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[98]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[99]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {col_out[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {quant_en[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {relu_en}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {scale[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {y_out[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {y_out[31]}]
set_load -pin_load 0.0334 [get_ports {y_out[30]}]
set_load -pin_load 0.0334 [get_ports {y_out[29]}]
set_load -pin_load 0.0334 [get_ports {y_out[28]}]
set_load -pin_load 0.0334 [get_ports {y_out[27]}]
set_load -pin_load 0.0334 [get_ports {y_out[26]}]
set_load -pin_load 0.0334 [get_ports {y_out[25]}]
set_load -pin_load 0.0334 [get_ports {y_out[24]}]
set_load -pin_load 0.0334 [get_ports {y_out[23]}]
set_load -pin_load 0.0334 [get_ports {y_out[22]}]
set_load -pin_load 0.0334 [get_ports {y_out[21]}]
set_load -pin_load 0.0334 [get_ports {y_out[20]}]
set_load -pin_load 0.0334 [get_ports {y_out[19]}]
set_load -pin_load 0.0334 [get_ports {y_out[18]}]
set_load -pin_load 0.0334 [get_ports {y_out[17]}]
set_load -pin_load 0.0334 [get_ports {y_out[16]}]
set_load -pin_load 0.0334 [get_ports {y_out[15]}]
set_load -pin_load 0.0334 [get_ports {y_out[14]}]
set_load -pin_load 0.0334 [get_ports {y_out[13]}]
set_load -pin_load 0.0334 [get_ports {y_out[12]}]
set_load -pin_load 0.0334 [get_ports {y_out[11]}]
set_load -pin_load 0.0334 [get_ports {y_out[10]}]
set_load -pin_load 0.0334 [get_ports {y_out[9]}]
set_load -pin_load 0.0334 [get_ports {y_out[8]}]
set_load -pin_load 0.0334 [get_ports {y_out[7]}]
set_load -pin_load 0.0334 [get_ports {y_out[6]}]
set_load -pin_load 0.0334 [get_ports {y_out[5]}]
set_load -pin_load 0.0334 [get_ports {y_out[4]}]
set_load -pin_load 0.0334 [get_ports {y_out[3]}]
set_load -pin_load 0.0334 [get_ports {y_out[2]}]
set_load -pin_load 0.0334 [get_ports {y_out[1]}]
set_load -pin_load 0.0334 [get_ports {y_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {relu_en}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[127]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[126]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[125]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[124]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[123]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[122]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[121]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[120]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[119]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[118]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[117]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[116]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[115]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[114]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[113]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[112]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[111]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[110]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[109]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[108]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[107]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[106]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[105]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[104]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[103]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[102]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[101]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[100]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[99]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[98]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[97]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[96]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[95]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[94]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[93]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[92]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[91]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[90]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[89]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[88]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[87]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[86]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[85]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[84]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[83]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[82]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[81]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[80]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[79]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[78]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[77]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[76]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[75]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[74]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[73]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[72]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[71]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[70]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[69]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[68]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[67]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[66]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[65]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[64]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[63]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[62]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[61]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[60]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[59]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[58]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[57]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[56]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {col_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {quant_en[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {scale[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 12.0000 [current_design]
