###############################################################################
# Created by write_sdc
###############################################################################
current_design gemm_pe
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 14.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_in[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_in[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_in[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_in[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bias[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {h_en_in}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_bias}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {v_en_in}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_in[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_in[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_in[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_in[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {a_out[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {acc_out[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {h_en_out}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {v_en_out}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_out[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_out[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_out[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {w_out[3]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {h_en_out}]
set_load -pin_load 0.0334 [get_ports {v_en_out}]
set_load -pin_load 0.0334 [get_ports {a_out[3]}]
set_load -pin_load 0.0334 [get_ports {a_out[2]}]
set_load -pin_load 0.0334 [get_ports {a_out[1]}]
set_load -pin_load 0.0334 [get_ports {a_out[0]}]
set_load -pin_load 0.0334 [get_ports {acc_out[15]}]
set_load -pin_load 0.0334 [get_ports {acc_out[14]}]
set_load -pin_load 0.0334 [get_ports {acc_out[13]}]
set_load -pin_load 0.0334 [get_ports {acc_out[12]}]
set_load -pin_load 0.0334 [get_ports {acc_out[11]}]
set_load -pin_load 0.0334 [get_ports {acc_out[10]}]
set_load -pin_load 0.0334 [get_ports {acc_out[9]}]
set_load -pin_load 0.0334 [get_ports {acc_out[8]}]
set_load -pin_load 0.0334 [get_ports {acc_out[7]}]
set_load -pin_load 0.0334 [get_ports {acc_out[6]}]
set_load -pin_load 0.0334 [get_ports {acc_out[5]}]
set_load -pin_load 0.0334 [get_ports {acc_out[4]}]
set_load -pin_load 0.0334 [get_ports {acc_out[3]}]
set_load -pin_load 0.0334 [get_ports {acc_out[2]}]
set_load -pin_load 0.0334 [get_ports {acc_out[1]}]
set_load -pin_load 0.0334 [get_ports {acc_out[0]}]
set_load -pin_load 0.0334 [get_ports {w_out[3]}]
set_load -pin_load 0.0334 [get_ports {w_out[2]}]
set_load -pin_load 0.0334 [get_ports {w_out[1]}]
set_load -pin_load 0.0334 [get_ports {w_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {h_en_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_bias}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {v_en_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {a_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bias[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {w_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {w_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {w_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {w_in[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
